### ISSUE TITLE
Applies to Issue

### ISSUE THREAD

**Issue by erniecraddock** [platform-experience/pi-multiform#4]
Good morning,
I forked the newest version to my instance and have an issue with child details when applies to Single screen is chosen. When showing an embedded list it works perfectly when applies to=All Screens. When apples to=Single Section and any section is chosen, the embedded list does not appear. I tried this on the sample problem->incident provided in the update set. Is there some configuration missing in order to select a specific section.

Thank you so much

Ernie

**Comment by dylanlindgren** [comment]
This is a known issue. The fix is to update the dictionary record for the **Form section** field on the **Multiform Child** table to point at the `sys_ui_section` table, rather than the `sys_ui_form_section` table.

This is the record you need to update:
`/sys_dictionary.do?sys_id=bb5599f71b7f09d0b1d5a7d6b04bcba2`
